In [1]:
import numpy as np

In [4]:
mat_a = np.arange(1,10).reshape(3,3)

In [12]:
mat_a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [10]:
mat_b = np.arange(9,0,-1).reshape(3,3)

In [13]:
mat_b

array([[9, 8, 7],
       [6, 5, 4],
       [3, 2, 1]])

In [11]:
mat_b.dot(mat_a)

array([[ 90, 114, 138],
       [ 54,  69,  84],
       [ 18,  24,  30]])

In [14]:
mat_a.dot(mat_b)

array([[ 30,  24,  18],
       [ 84,  69,  54],
       [138, 114,  90]])

In [15]:
from gensim.models import Word2Vec

In [17]:
text = ['This is a really delicious slice of pie, Mrs. Smith',
       'Are you sure that pie is really the best choice given your condition?',
       'Certainly, there are better things for you to eat.']

In [19]:
vector_model = Word2Vec(text)

In [20]:
vector_model.

10000